---
# The purpose of this file is to define the account catalog for the site. This
# mostly contains service usernames, but also contain some information which
# should be changed like the region (site) name.
schema: pegleg/AccountCatalogue/v1
metadata:
  schema: metadata/Document/v1
  name: ucp_service_accounts
  layeringDefinition:
    abstract: false
    layer: site
  storagePolicy: cleartext
data:
    ucp:
        postgres:
            admin:
                username: postgres
            replica:
                username: standby
            exporter:
                username: psql_exporter
        oslo_db:
            admin:
                username: root
        oslo_messaging:
            admin:
                username: rabbitmq
        keystone:
            admin:
                # NEWSITE-CHANGEME: Replace with the site name
                region_name: RegionOne
                username: admin
                project_name: admin
                user_domain_name: default
                project_domain_name: default
            oslo_messaging:
                admin:
                    username: rabbitmq
                keystone:
                    username: keystone
            oslo_db:
                username: keystone
                database: keystone
        promenade:
            keystone:
                # NEWSITE-CHANGEME: Replace with the site name
                region_name: RegionOne
                role: admin
                project_name: service
                project_domain_name: default
                user_domain_name: default
                username: promenade
        drydock:
            keystone:
                # NEWSITE-CHANGEME: Replace with the site name
                region_name: RegionOne
                role: admin
                project_name: service
                project_domain_name: default
                user_domain_name: default
                username: drydock
            postgres:
                username: drydock
                database: drydock
        shipyard:
            keystone:
                # NEWSITE-CHANGEME: Replace with the site name
                region_name: RegionOne
                role: admin
                project_name: service
                project_domain_name: default
                user_domain_name: default
                username: shipyard
            postgres:
                username: shipyard
                database: shipyard
        airflow:
            postgres:
                username: airflow
                database: airflow
            oslo_messaging:
                admin:
                    username: rabbitmq
                user:
                    username: airflow
        maas:
            admin:
                username: admin
                email: none@none
            postgres:
                username: maas
                database: maasdb
        barbican:
            keystone:
                # NEWSITE-CHANGEME: Replace with the site name
                region_name: RegionOne
                role: admin
                project_name: service
                project_domain_name: default
                user_domain_name: default
                username: barbican
            oslo_db:
                username: barbican
                database: barbican
            oslo_messaging:
                admin:
                    username: rabbitmq
                keystone:
                    username: keystone
        armada:
            keystone:
                project_domain_name: default
                user_domain_name: default
                project_name: service
                # NEWSITE-CHANGEME: Replace with the site name
                region_name: RegionOne
                role: admin
                username: armada
        deckhand:
            keystone:
                # NEWSITE-CHANGEME: Replace with the site name
                region_name: RegionOne
                role: admin
                project_name: service
                project_domain_name: default
                user_domain_name: default
                username: deckhand
            postgres:
                username: deckhand
                database: deckhand
        prometheus_openstack_exporter:
            user:
                region_name: RegionOne
                role: admin
                username: prometheus-openstack-exporter
                project_name: service
                user_domain_name: default
                project_domain_name: default
    ceph:
        swift:
            keystone:
                role: admin
                # NEWSITE-CHANGEME: Replace with the site name
                region_name: RegionOne
                username: swift
                project_name: service
                user_domain_name: default
                project_domain_name: default
...
---
schema: pegleg/AccountCatalogue/v1
metadata:
  schema: metadata/Document/v1
  name: osh_infra_service_accounts
  layeringDefinition:
    abstract: false
    layer: site
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/CommonSoftwareConfig/v1
        name: common-software-config
        path: .osh.region_name
      dest:
        path: .osh_infra.prometheus_openstack_exporter.user.region_name
data:
  osh_infra:
    ceph_object_store:
      admin:
        username: s3_admin
      elasticsearch:
        username: elasticsearch
    grafana:
      admin:
        username: grafana
      oslo_db:
        username: grafana
        database: grafana
      oslo_db_session:
        username: grafana_session
        database: grafana_session
    elasticsearch:
      admin:
        username: elasticsearch
    oslo_db:
      admin:
        username: root
    prometheus_mysql_exporter:
      user:
        username: osh-infra-oslodb-exporter
    prometheus_openstack_exporter:
      user:
        role: admin
        username: prometheus-openstack-exporter
        project_name: service
        user_domain_name: default
        project_domain_name: default
    nagios:
      admin:
        username: nagios
    prometheus:
      admin:
        username: prometheus
    ldap:
      admin:
        # NEWSITE-CHANGEME: Replace with the site's LDAP account used to
        # authenticate to the active directory backend to validate keystone
        # users.
        bind: "test@ldap.example.com"
...
